# Generated by Django 5.1.2 on 2025-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcfBogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tread_diameter_new', models.CharField(blank=True, max_length=100, null=True)),
                ('last_shop_issue_size_dia', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_worn_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('wheel_back_to_back', models.CharField(blank=True, max_length=100, null=True)),
                ('back_to_back_worn_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('flange_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('flange_thickness_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('flange_height', models.CharField(blank=True, max_length=100, null=True)),
                ('flange_height_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('tread_hollow', models.CharField(blank=True, max_length=100, null=True)),
                ('tread_hollow_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('wheel_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcfWheelMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tread_diameter', models.FloatField()),
                ('last_shop_issue_size', models.FloatField()),
                ('condemning_dia', models.FloatField()),
                ('wheel_gauge', models.FloatField()),
                ('permissible_variation_same_axle', models.CharField(default='0.5', max_length=50)),
                ('permissible_variation_same_bogie', models.CharField(default='5', max_length=50)),
                ('permissible_variation_same_coach', models.CharField(default='13', max_length=50)),
                ('wheel_profile', models.CharField(default='29.4 Flange Thickness', max_length=100)),
                ('intermediate_wwp', models.CharField(default='20 TO 28', max_length=100)),
                ('bearing_seat_diameter', models.CharField(default='130.043 TO 130.068', max_length=100)),
                ('roller_bearing_outer_dia', models.CharField(max_length=100)),
                ('roller_bearing_bore_dia', models.CharField(max_length=100)),
                ('roller_bearing_width', models.CharField(max_length=100)),
                ('axle_box_housing_bore_dia', models.CharField(max_length=100)),
                ('wheel_disc_width', models.CharField(max_length=100)),
            ],
        ),
    ]
